import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      
      <body className={inter.className}>
        <nav>
          <ul className="flex justify-evenly">
            <li>
              <Link className="text-5xl" href="/">
                Home
              </Link>
            </li>
            <li>
              <Link className="text-5xl" href="/login">
                Login
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
